---
title: "hwBayes2"
author: "Alexander Grunenwald"
date: "2024-09-21"
output: pdf_document
---


[question1](1000018242.jpg)
```{r}
n <- 100; s<- 57
a<-1; b<-1
qbeta(c(.025, .975), a+s, b+n-s) #c

# d
n <- 100; s<- 57
a<-3; b<-1
qbeta(c(.025, .975), a+s, b+n-s)

n <- 100; s<- 57
a<-1; b<-3
qbeta(c(.025, .975), a+s, b+n-s)

#e
a<-1; b <-1

theat.prior.mc <- rbeta(10000, a,b)
gamma.prior.mc <- log(theat.prior.mc/(1- theat.prior.mc))
n0 <- 100 - 57; n1 <- 57
theat.post.mc <- rbeta(10000, a +n1, b + n0)
gamma.post.mc <- log(theat.post.mc/(1- theat.post.mc))
quantile(gamma.post.mc, c(0.025, 0.975))
mean(gamma.post.mc)

library(ggplot2)

data <- data.frame(
  value = c(gamma.prior.mc, gamma.post.mc),
  group = c(rep("Prior", length(gamma.prior.mc)), rep("Posterior", length(gamma.post.mc)))
)

ggplot(data, aes(x = value, color = group)) +
  geom_density() +
  labs(title = "Prior and Posterior Densities", x = "Value", y = "Density") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red")) +
  theme(legend.title = element_blank())

```


[question2 and 3a](1000018249.jpg)
```{r}
# for question 2 -------------------------------------------------------------------------------------
yA <- c(12, 9, 12, 14, 13, 13, 15, 8, 15, 6)
yB <- c(11, 11, 10, 9, 9, 8, 7, 10, 6, 8, 8, 9, 7)

Ta <- sum(yA) #sufficent Statistic
Tb <- sum(yB) # Sufficent Statistic

aA <- 120 + Ta ;bA <- 10 + 10 
aB <- 12 + Tb; bB <- 1 + 13 # 13 is the number of observations in yB

# b
gamma.a.posterior <- rgamma(10000, aA, bA)
gamma.b.posterior <- rgamma(10000, aB, bB)
par(mfrow=(c(1,2)))
plot(density(gamma.a.posterior))
plot(density(gamma.b.posterior))

interval.a <- quantile(gamma.a.posterior, c(0.025, .975))
interval.b <- quantile(gamma.b.posterior, c(0.025, .975))
paste("Interval A is: ", interval.a, "\nInterval B is: ", interval.b)

# c
theat.ratio <- gamma.a.posterior/gamma.b.posterior

plot(density(theat.ratio))
mean.ratio <- mean(theat.ratio)
interval.ratio <- quantile(theat.ratio, c(0.025, 0.975))


#answer for e
posterior.a <- gamma.a.posterior
posterior.b.func <- function(n){
  return(rgamma(10000, (12 + bB)*n, n0 + 13))
}

n_vals <- c(1:100)
posterior.probas <- array(dim = 100)
for (n in n_vals){
  posterior.b.n <- posterior.b.func(n)
  posterior.probas[n] = mean(posterior.a>posterior.b.n)
}

plot(n_vals, posterior.probas, type = 'b', xlab = "n0", ylab = "P(ThetaA > ThetaB)", 
     main = "Posterior Probability P(ThetaA > ThetaB) vs n0")
```


[question3b and 4](1000018243.jpg)